/**
 * @license Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
/**
 * @module emojis/emojisflags
 */
import { Plugin } from 'ckeditor5/src/core.js';
import type Emojis from './emojis.js';

/**
 * A plugin that provides special characters for the "Flags" category.
 *
 * ```ts
 * ClassicEditor
 *   .create( {
 *     plugins: [ ..., Emojis, EmojisFlags ],
 *   } )
 *   .then( ... )
 *   .catch( ... );
 * ```
 */
export default class EmojisFlags extends Plugin {
    /**
     * @inheritDoc
     */
    public static get pluginName() {
        return 'EmojisFlags' as const;
    }
    /**
     * @inheritDoc
     */
    public init(): void {
        const editor = this.editor;
        const t = editor.t;
        const plugin: Emojis = editor.plugins.get('Emojis');

        plugin.addItems('Flags', [
            { character: '🏁', title: t('Chequered Flag') },
            { character: '🚩', title: t('Triangular Flag') },
            { character: '🎌', title: t('Crossed Flags') },
            { character: '🏴', title: t('Black Flag') },
            { character: '🏳️', title: t('White Flag') },
            { character: '🏳️‍🌈', title: t('Rainbow Flag') },
            { character: '🏳️‍⚧️', title: t('Transgender Flag') },
            { character: '🏴‍☠️', title: t('Pirate Flag') },
            { character: '🇦🇨', title: t('Flag: Ascension Island') },
            { character: '🇦🇩', title: t('Flag: Andorra') },
            { character: '🇦🇪', title: t('Flag: United Arab Emirates') },
            { character: '🇦🇫', title: t('Flag: Afghanistan') },
            { character: '🇦🇬', title: t('Flag: Antigua & Barbuda') },
            { character: '🇦🇮', title: t('Flag: Anguilla') },
            { character: '🇦🇱', title: t('Flag: Albania') },
            { character: '🇦🇲', title: t('Flag: Armenia') },
            { character: '🇦🇴', title: t('Flag: Angola') },
            { character: '🇦🇶', title: t('Flag: Antarctica') },
            { character: '🇦🇷', title: t('Flag: Argentina') },
            { character: '🇦🇸', title: t('Flag: American Samoa') },
            { character: '🇦🇹', title: t('Flag: Austria') },
            { character: '🇦🇺', title: t('Flag: Australia') },
            { character: '🇦🇼', title: t('Flag: Aruba') },
            { character: '🇦🇽', title: t('Flag: Åland Islands') },
            { character: '🇦🇿', title: t('Flag: Azerbaijan') },
            { character: '🇧🇦', title: t('Flag: Bosnia & Herzegovina') },
            { character: '🇧🇧', title: t('Flag: Barbados') },
            { character: '🇧🇩', title: t('Flag: Bangladesh') },
            { character: '🇧🇪', title: t('Flag: Belgium') },
            { character: '🇧🇫', title: t('Flag: Burkina Faso') },
            { character: '🇧🇬', title: t('Flag: Bulgaria') },
            { character: '🇧🇭', title: t('Flag: Bahrain') },
            { character: '🇧🇮', title: t('Flag: Burundi') },
            { character: '🇧🇯', title: t('Flag: Benin') },
            { character: '🇧🇱', title: t('Flag: St. Barthélemy') },
            { character: '🇧🇲', title: t('Flag: Bermuda') },
            { character: '🇧🇳', title: t('Flag: Brunei') },
            { character: '🇧🇴', title: t('Flag: Bolivia') },
            { character: '🇧🇶', title: t('Flag: Caribbean Netherlands') },
            { character: '🇧🇷', title: t('Flag: Brazil') },
            { character: '🇧🇸', title: t('Flag: Bahamas') },
            { character: '🇧🇹', title: t('Flag: Bhutan') },
            { character: '🇧🇻', title: t('Flag: Bouvet Island') },
            { character: '🇧🇼', title: t('Flag: Botswana') },
            { character: '🇧🇾', title: t('Flag: Belarus') },
            { character: '🇧🇿', title: t('Flag: Belize') },
            { character: '🇨🇦', title: t('Flag: Canada') },
            { character: '🇨🇨', title: t('Flag: Cocos (Keeling) Islands') },
            { character: '🇨🇩', title: t('Flag: Congo - Kinshasa') },
            { character: '🇨🇫', title: t('Flag: Central African Republic') },
            { character: '🇨🇬', title: t('Flag: Congo - Brazzaville') },
            { character: '🇨🇭', title: t('Flag: Switzerland') },
            { character: '🇨🇮', title: t('Flag: Côte d’Ivoire') },
            { character: '🇨🇰', title: t('Flag: Cook Islands') },
            { character: '🇨🇱', title: t('Flag: Chile') },
            { character: '🇨🇲', title: t('Flag: Cameroon') },
            { character: '🇨🇳', title: t('Flag: China') },
            { character: '🇨🇴', title: t('Flag: Colombia') },
            { character: '🇨🇵', title: t('Flag: Clipperton Island') },
            { character: '🇨🇷', title: t('Flag: Costa Rica') },
            { character: '🇨🇺', title: t('Flag: Cuba') },
            { character: '🇨🇻', title: t('Flag: Cape Verde') },
            { character: '🇨🇼', title: t('Flag: Curaçao') },
            { character: '🇨🇽', title: t('Flag: Christmas Island') },
            { character: '🇨🇾', title: t('Flag: Cyprus') },
            { character: '🇨🇿', title: t('Flag: Czechia') },
            { character: '🇩🇪', title: t('Flag: Germany') },
            { character: '🇩🇬', title: t('Flag: Diego Garcia') },
            { character: '🇩🇯', title: t('Flag: Djibouti') },
            { character: '🇩🇰', title: t('Flag: Denmark') },
            { character: '🇩🇲', title: t('Flag: Dominica') },
            { character: '🇩🇴', title: t('Flag: Dominican Republic') },
            { character: '🇩🇿', title: t('Flag: Algeria') },
            { character: '🇪🇦', title: t('Flag: Ceuta & Melilla') },
            { character: '🇪🇨', title: t('Flag: Ecuador') },
            { character: '🇪🇪', title: t('Flag: Estonia') },
            { character: '🇪🇬', title: t('Flag: Egypt') },
            { character: '🇪🇭', title: t('Flag: Western Sahara') },
            { character: '🇪🇷', title: t('Flag: Eritrea') },
            { character: '🇪🇸', title: t('Flag: Spain') },
            { character: '🇪🇹', title: t('Flag: Ethiopia') },
            { character: '🇪🇺', title: t('Flag: European Union') },
            { character: '🇫🇮', title: t('Flag: Finland') },
            { character: '🇫🇯', title: t('Flag: Fiji') },
            { character: '🇫🇰', title: t('Flag: Falkland Islands') },
            { character: '🇫🇲', title: t('Flag: Micronesia') },
            { character: '🇫🇴', title: t('Flag: Faroe Islands') },
            { character: '🇫🇷', title: t('Flag: France') },
            { character: '🇬🇦', title: t('Flag: Gabon') },
            { character: '🇬🇧', title: t('Flag: United Kingdom') },
            { character: '🇬🇩', title: t('Flag: Grenada') },
            { character: '🇬🇪', title: t('Flag: Georgia') },
            { character: '🇬🇫', title: t('Flag: French Guiana') },
            { character: '🇬🇬', title: t('Flag: Guernsey') },
            { character: '🇬🇭', title: t('Flag: Ghana') },
            { character: '🇬🇮', title: t('Flag: Gibraltar') },
            { character: '🇬🇱', title: t('Flag: Greenland') },
            { character: '🇬🇲', title: t('Flag: Gambia') },
            { character: '🇬🇳', title: t('Flag: Guinea') },
            { character: '🇬🇵', title: t('Flag: Guadeloupe') },
            { character: '🇬🇶', title: t('Flag: Equatorial Guinea') },
            { character: '🇬🇷', title: t('Flag: Greece') },
            { character: '🇬🇸', title: t('Flag: South Georgia & South Sandwich Islands') },
            { character: '🇬🇹', title: t('Flag: Guatemala') },
            { character: '🇬🇺', title: t('Flag: Guam') },
            { character: '🇬🇼', title: t('Flag: Guinea-Bissau') },
            { character: '🇬🇾', title: t('Flag: Guyana') },
            { character: '🇭🇰', title: t('Flag: Hong Kong SAR China') },
            { character: '🇭🇲', title: t('Flag: Heard & McDonald Islands') },
            { character: '🇭🇳', title: t('Flag: Honduras') },
            { character: '🇭🇷', title: t('Flag: Croatia') },
            { character: '🇭🇹', title: t('Flag: Haiti') },
            { character: '🇭🇺', title: t('Flag: Hungary') },
            { character: '🇮🇨', title: t('Flag: Canary Islands') },
            { character: '🇮🇩', title: t('Flag: Indonesia') },
            { character: '🇮🇪', title: t('Flag: Ireland') },
            { character: '🇮🇱', title: t('Flag: Israel') },
            { character: '🇮🇲', title: t('Flag: Isle of Man') },
            { character: '🇮🇳', title: t('Flag: India') },
            { character: '🇮🇴', title: t('Flag: British Indian Ocean Territory') },
            { character: '🇮🇶', title: t('Flag: Iraq') },
            { character: '🇮🇷', title: t('Flag: Iran') },
            { character: '🇮🇸', title: t('Flag: Iceland') },
            { character: '🇮🇹', title: t('Flag: Italy') },
            { character: '🇯🇪', title: t('Flag: Jersey') },
            { character: '🇯🇲', title: t('Flag: Jamaica') },
            { character: '🇯🇴', title: t('Flag: Jordan') },
            { character: '🇯🇵', title: t('Flag: Japan') },
            { character: '🇰🇪', title: t('Flag: Kenya') },
            { character: '🇰🇬', title: t('Flag: Kyrgyzstan') },
            { character: '🇰🇭', title: t('Flag: Cambodia') },
            { character: '🇰🇮', title: t('Flag: Kiribati') },
            { character: '🇰🇲', title: t('Flag: Comoros') },
            { character: '🇰🇳', title: t('Flag: St. Kitts & Nevis') },
            { character: '🇰🇵', title: t('Flag: North Korea') },
            { character: '🇰🇷', title: t('Flag: South Korea') },
            { character: '🇰🇼', title: t('Flag: Kuwait') },
            { character: '🇰🇾', title: t('Flag: Cayman Islands') },
            { character: '🇰🇿', title: t('Flag: Kazakhstan') },
            { character: '🇱🇦', title: t('Flag: Laos') },
            { character: '🇱🇧', title: t('Flag: Lebanon') },
            { character: '🇱🇨', title: t('Flag: St. Lucia') },
            { character: '🇱🇮', title: t('Flag: Liechtenstein') },
            { character: '🇱🇰', title: t('Flag: Sri Lanka') },
            { character: '🇱🇷', title: t('Flag: Liberia') },
            { character: '🇱🇸', title: t('Flag: Lesotho') },
            { character: '🇱🇹', title: t('Flag: Lithuania') },
            { character: '🇱🇺', title: t('Flag: Luxembourg') },
            { character: '🇱🇻', title: t('Flag: Latvia') },
            { character: '🇱🇾', title: t('Flag: Libya') },
            { character: '🇲🇦', title: t('Flag: Morocco') },
            { character: '🇲🇨', title: t('Flag: Monaco') },
            { character: '🇲🇩', title: t('Flag: Moldova') },
            { character: '🇲🇪', title: t('Flag: Montenegro') },
            { character: '🇲🇫', title: t('Flag: St. Martin') },
            { character: '🇲🇬', title: t('Flag: Madagascar') },
            { character: '🇲🇭', title: t('Flag: Marshall Islands') },
            { character: '🇲🇰', title: t('Flag: North Macedonia') },
            { character: '🇲🇱', title: t('Flag: Mali') },
            { character: '🇲🇲', title: t('Flag: Myanmar (Burma)') },
            { character: '🇲🇳', title: t('Flag: Mongolia') },
            { character: '🇲🇴', title: t('Flag: Macao SAR China') },
            { character: '🇲🇵', title: t('Flag: Northern Mariana Islands') },
            { character: '🇲🇶', title: t('Flag: Martinique') },
            { character: '🇲🇷', title: t('Flag: Mauritania') },
            { character: '🇲🇸', title: t('Flag: Montserrat') },
            { character: '🇲🇹', title: t('Flag: Malta') },
            { character: '🇲🇺', title: t('Flag: Mauritius') },
            { character: '🇲🇻', title: t('Flag: Maldives') },
            { character: '🇲🇼', title: t('Flag: Malawi') },
            { character: '🇲🇽', title: t('Flag: Mexico') },
            { character: '🇲🇾', title: t('Flag: Malaysia') },
            { character: '🇲🇿', title: t('Flag: Mozambique') },
            { character: '🇳🇦', title: t('Flag: Namibia') },
            { character: '🇳🇨', title: t('Flag: New Caledonia') },
            { character: '🇳🇪', title: t('Flag: Niger') },
            { character: '🇳🇫', title: t('Flag: Norfolk Island') },
            { character: '🇳🇬', title: t('Flag: Nigeria') },
            { character: '🇳🇮', title: t('Flag: Nicaragua') },
            { character: '🇳🇱', title: t('Flag: Netherlands') },
            { character: '🇳🇴', title: t('Flag: Norway') },
            { character: '🇳🇵', title: t('Flag: Nepal') },
            { character: '🇳🇷', title: t('Flag: Nauru') },
            { character: '🇳🇺', title: t('Flag: Niue') },
            { character: '🇳🇿', title: t('Flag: New Zealand') },
            { character: '🇴🇲', title: t('Flag: Oman') },
            { character: '🇵🇦', title: t('Flag: Panama') },
            { character: '🇵🇪', title: t('Flag: Peru') },
            { character: '🇵🇫', title: t('Flag: French Polynesia') },
            { character: '🇵🇬', title: t('Flag: Papua New Guinea') },
            { character: '🇵🇭', title: t('Flag: Philippines') },
            { character: '🇵🇰', title: t('Flag: Pakistan') },
            { character: '🇵🇱', title: t('Flag: Poland') },
            { character: '🇵🇲', title: t('Flag: St. Pierre & Miquelon') },
            { character: '🇵🇳', title: t('Flag: Pitcairn Islands') },
            { character: '🇵🇷', title: t('Flag: Puerto Rico') },
            { character: '🇵🇸', title: t('Flag: Palestinian Territories') },
            { character: '🇵🇹', title: t('Flag: Portugal') },
            { character: '🇵🇼', title: t('Flag: Palau') },
            { character: '🇵🇾', title: t('Flag: Paraguay') },
            { character: '🇶🇦', title: t('Flag: Qatar') },
            { character: '🇷🇪', title: t('Flag: Réunion') },
            { character: '🇷🇴', title: t('Flag: Romania') },
            { character: '🇷🇸', title: t('Flag: Serbia') },
            { character: '🇷🇺', title: t('Flag: Russia') },
            { character: '🇷🇼', title: t('Flag: Rwanda') },
            { character: '🇸🇦', title: t('Flag: Saudi Arabia') },
            { character: '🇸🇧', title: t('Flag: Solomon Islands') },
            { character: '🇸🇨', title: t('Flag: Seychelles') },
            { character: '🇸🇩', title: t('Flag: Sudan') },
            { character: '🇸🇪', title: t('Flag: Sweden') },
            { character: '🇸🇬', title: t('Flag: Singapore') },
            { character: '🇸🇭', title: t('Flag: St. Helena') },
            { character: '🇸🇮', title: t('Flag: Slovenia') },
            { character: '🇸🇯', title: t('Flag: Svalbard & Jan Mayen') },
            { character: '🇸🇰', title: t('Flag: Slovakia') },
            { character: '🇸🇱', title: t('Flag: Sierra Leone') },
            { character: '🇸🇲', title: t('Flag: San Marino') },
            { character: '🇸🇳', title: t('Flag: Senegal') },
            { character: '🇸🇴', title: t('Flag: Somalia') },
            { character: '🇸🇷', title: t('Flag: Suriname') },
            { character: '🇸🇸', title: t('Flag: South Sudan') },
            { character: '🇸🇹', title: t('Flag: São Tomé & Príncipe') },
            { character: '🇸🇻', title: t('Flag: El Salvador') },
            { character: '🇸🇽', title: t('Flag: Sint Maarten') },
            { character: '🇸🇾', title: t('Flag: Syria') },
            { character: '🇸🇿', title: t('Flag: Eswatini') },
            { character: '🇹🇦', title: t('Flag: Tristan da Cunha') },
            { character: '🇹🇨', title: t('Flag: Turks & Caicos Islands') },
            { character: '🇹🇩', title: t('Flag: Chad') },
            { character: '🇹🇫', title: t('Flag: French Southern Territories') },
            { character: '🇹🇬', title: t('Flag: Togo') },
            { character: '🇹🇭', title: t('Flag: Thailand') },
            { character: '🇹🇯', title: t('Flag: Tajikistan') },
            { character: '🇹🇰', title: t('Flag: Tokelau') },
            { character: '🇹🇱', title: t('Flag: Timor-Leste') },
            { character: '🇹🇲', title: t('Flag: Turkmenistan') },
            { character: '🇹🇳', title: t('Flag: Tunisia') },
            { character: '🇹🇴', title: t('Flag: Tonga') },
            { character: '🇹🇷', title: t('Flag: Turkey') },
            { character: '🇹🇹', title: t('Flag: Trinidad & Tobago') },
            { character: '🇹🇻', title: t('Flag: Tuvalu') },
            { character: '🇹🇼', title: t('Flag: Taiwan') },
            { character: '🇹🇿', title: t('Flag: Tanzania') },
            { character: '🇺🇦', title: t('Flag: Ukraine') },
            { character: '🇺🇬', title: t('Flag: Uganda') },
            { character: '🇺🇲', title: t('Flag: U.S. Outlying Islands') },
            { character: '🇺🇳', title: t('Flag: United Nations') },
            { character: '🇺🇸', title: t('Flag: United States') },
            { character: '🇺🇾', title: t('Flag: Uruguay') },
            { character: '🇺🇿', title: t('Flag: Uzbekistan') },
            { character: '🇻🇦', title: t('Flag: Vatican City') },
            { character: '🇻🇨', title: t('Flag: St. Vincent & Grenadines') },
            { character: '🇻🇪', title: t('Flag: Venezuela') },
            { character: '🇻🇬', title: t('Flag: British Virgin Islands') },
            { character: '🇻🇮', title: t('Flag: U.S. Virgin Islands') },
            { character: '🇻🇳', title: t('Flag: Vietnam') },
            { character: '🇻🇺', title: t('Flag: Vanuatu') },
            { character: '🇼🇫', title: t('Flag: Wallis & Futuna') },
            { character: '🇼🇸', title: t('Flag: Samoa') },
            { character: '🇽🇰', title: t('Flag: Kosovo') },
            { character: '🇾🇪', title: t('Flag: Yemen') },
            { character: '🇾🇹', title: t('Flag: Mayotte') },
            { character: '🇿🇦', title: t('Flag: South Africa') },
            { character: '🇿🇲', title: t('Flag: Zambia') },
            { character: '🇿🇼', title: t('Flag: Zimbabwe') },
            { character: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', title: t('Flag: England') },
            { character: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', title: t('Flag: Scotland') },
            { character: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', title: t('Flag: Wales') },
        ], { label: '🏁' + t('Flags') });
    }
}
