/**
 * @license Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
/**
 * @module emojis/emojisnature
 */
import { Plugin } from 'ckeditor5/src/core.js';
import type Emojis from './emojis.js';

/**
 * A plugin that provides special characters for the "Nature" category.
 *
 * ```ts
 * ClassicEditor
 *   .create( {
 *     plugins: [ ..., Emojis, EmojisNature ],
 *   } )
 *   .then( ... )
 *   .catch( ... );
 * ```
 */
export default class EmojisNature extends Plugin {
    /**
     * @inheritDoc
     */
    public static get pluginName() {
        return 'EmojisNature' as const;
    }
    /**
     * @inheritDoc
     */
    public init(): void {
        const editor = this.editor;
        const t = editor.t;
        const plugin: Emojis = editor.plugins.get('Emojis');

        plugin.addItems('Nature', [
            { character: '🙈', title: t('See-No-Evil Monkey') },
            { character: '🙉', title: t('Hear-No-Evil Monkey') },
            { character: '🙊', title: t('Speak-No-Evil Monkey') },
            { character: '💥', title: t('Collision') },
            { character: '💫', title: t('Dizzy') },
            { character: '💦', title: t('Sweat Droplets') },
            { character: '💨', title: t('Dashing Away') },
            { character: '🐵', title: t('Monkey Face') },
            { character: '🐒', title: t('Monkey') },
            { character: '🦍', title: t('Gorilla') },
            { character: '🦧', title: t('Orangutan') },
            { character: '🐶', title: t('Dog Face') },
            { character: '🐕', title: t('Dog') },
            { character: '🦮', title: t('Guide Dog') },
            { character: '🐕‍🦺', title: t('Service Dog') },
            { character: '🐩', title: t('Poodle') },
            { character: '🐺', title: t('Wolf') },
            { character: '🦊', title: t('Fox') },
            { character: '🦝', title: t('Raccoon') },
            { character: '🐱', title: t('Cat Face') },
            { character: '🐈', title: t('Cat') },
            { character: '🐈‍⬛', title: t('Black Cat') },
            { character: '🦁', title: t('Lion') },
            { character: '🐯', title: t('Tiger Face') },
            { character: '🐅', title: t('Tiger') },
            { character: '🐆', title: t('Leopard') },
            { character: '🐴', title: t('Horse Face') },
            { character: '🐎', title: t('Horse') },
            { character: '🦄', title: t('Unicorn') },
            { character: '🦓', title: t('Zebra') },
            { character: '🦌', title: t('Deer') },
            { character: '🦬', title: t('Bison') },
            { character: '🐮', title: t('Cow Face') },
            { character: '🐂', title: t('Ox') },
            { character: '🐃', title: t('Water Buffalo') },
            { character: '🐄', title: t('Cow') },
            { character: '🐷', title: t('Pig Face') },
            { character: '🐖', title: t('Pig') },
            { character: '🐗', title: t('Boar') },
            { character: '🐽', title: t('Pig Nose') },
            { character: '🐏', title: t('Ram') },
            { character: '🐑', title: t('Ewe') },
            { character: '🐐', title: t('Goat') },
            { character: '🐪', title: t('Camel') },
            { character: '🐫', title: t('Two-Hump Camel') },
            { character: '🦙', title: t('Llama') },
            { character: '🦒', title: t('Giraffe') },
            { character: '🐘', title: t('Elephant') },
            { character: '🦣', title: t('Mammoth') },
            { character: '🦏', title: t('Rhinoceros') },
            { character: '🦛', title: t('Hippopotamus') },
            { character: '🐭', title: t('Mouse Face') },
            { character: '🐁', title: t('Mouse') },
            { character: '🐀', title: t('Rat') },
            { character: '🐹', title: t('Hamster') },
            { character: '🐰', title: t('Rabbit Face') },
            { character: '🐇', title: t('Rabbit') },
            { character: '🐿️', title: t('Chipmunk') },
            { character: '🦫', title: t('Beaver') },
            { character: '🦔', title: t('Hedgehog') },
            { character: '🦇', title: t('Bat') },
            { character: '🐻', title: t('Bear') },
            { character: '🐻‍❄️', title: t('Polar Bear') },
            { character: '🐨', title: t('Koala') },
            { character: '🐼', title: t('Panda') },
            { character: '🦥', title: t('Sloth') },
            { character: '🦦', title: t('Otter') },
            { character: '🦨', title: t('Skunk') },
            { character: '🦘', title: t('Kangaroo') },
            { character: '🦡', title: t('Badger') },
            { character: '🐾', title: t('Paw Prints') },
            { character: '🦃', title: t('Turkey') },
            { character: '🐔', title: t('Chicken') },
            { character: '🐓', title: t('Rooster') },
            { character: '🐣', title: t('Hatching Chick') },
            { character: '🐤', title: t('Baby Chick') },
            { character: '🐥', title: t('Front-Facing Baby Chick') },
            { character: '🐦', title: t('Bird') },
            { character: '🐧', title: t('Penguin') },
            { character: '🕊️', title: t('Dove') },
            { character: '🦅', title: t('Eagle') },
            { character: '🦆', title: t('Duck') },
            { character: '🦢', title: t('Swan') },
            { character: '🦉', title: t('Owl') },
            { character: '🦤', title: t('Dodo') },
            { character: '🪶', title: t('Feather') },
            { character: '🦩', title: t('Flamingo') },
            { character: '🦚', title: t('Peacock') },
            { character: '🦜', title: t('Parrot') },
            { character: '🐸', title: t('Frog') },
            { character: '🐊', title: t('Crocodile') },
            { character: '🐢', title: t('Turtle') },
            { character: '🦎', title: t('Lizard') },
            { character: '🐍', title: t('Snake') },
            { character: '🐲', title: t('Dragon Face') },
            { character: '🐉', title: t('Dragon') },
            { character: '🦕', title: t('Sauropod') },
            { character: '🦖', title: t('T-Rex') },
            { character: '🐳', title: t('Spouting Whale') },
            { character: '🐋', title: t('Whale') },
            { character: '🐬', title: t('Dolphin') },
            { character: '🦭', title: t('Seal') },
            { character: '🐟', title: t('Fish') },
            { character: '🐠', title: t('Tropical Fish') },
            { character: '🐡', title: t('Blowfish') },
            { character: '🦈', title: t('Shark') },
            { character: '🐙', title: t('Octopus') },
            { character: '🐚', title: t('Spiral Shell') },
            { character: '🐌', title: t('Snail') },
            { character: '🦋', title: t('Butterfly') },
            { character: '🐛', title: t('Bug') },
            { character: '🐜', title: t('Ant') },
            { character: '🐝', title: t('Honeybee') },
            { character: '🪲', title: t('Beetle') },
            { character: '🐞', title: t('Lady Beetle') },
            { character: '🦗', title: t('Cricket') },
            { character: '🪳', title: t('Cockroach') },
            { character: '🕷️', title: t('Spider') },
            { character: '🕸️', title: t('Spider Web') },
            { character: '🦂', title: t('Scorpion') },
            { character: '🦟', title: t('Mosquito') },
            { character: '🪰', title: t('Fly') },
            { character: '🪱', title: t('Worm') },
            { character: '🦠', title: t('Microbe') },
            { character: '💐', title: t('Bouquet') },
            { character: '🌸', title: t('Cherry Blossom') },
            { character: '💮', title: t('White Flower') },
            { character: '🏵️', title: t('Rosette') },
            { character: '🌹', title: t('Rose') },
            { character: '🥀', title: t('Wilted Flower') },
            { character: '🌺', title: t('Hibiscus') },
            { character: '🌻', title: t('Sunflower') },
            { character: '🌼', title: t('Blossom') },
            { character: '🌷', title: t('Tulip') },
            { character: '🌱', title: t('Seedling') },
            { character: '🪴', title: t('Potted Plant') },
            { character: '🌲', title: t('Evergreen Tree') },
            { character: '🌳', title: t('Deciduous Tree') },
            { character: '🌴', title: t('Palm Tree') },
            { character: '🌵', title: t('Cactus') },
            { character: '🌾', title: t('Sheaf of Rice') },
            { character: '🌿', title: t('Herb') },
            { character: '☘️', title: t('Shamrock') },
            { character: '🍀', title: t('Four Leaf Clover') },
            { character: '🍁', title: t('Maple Leaf') },
            { character: '🍂', title: t('Fallen Leaf') },
            { character: '🍃', title: t('Leaf Fluttering in Wind') },
            { character: '🍄', title: t('Mushroom') },
            { character: '🌰', title: t('Chestnut') },
            { character: '🦀', title: t('Crab') },
            { character: '🦞', title: t('Lobster') },
            { character: '🦐', title: t('Shrimp') },
            { character: '🦑', title: t('Squid') },
            { character: '🌍', title: t('Globe Showing Europe-Africa') },
            { character: '🌎', title: t('Globe Showing Americas') },
            { character: '🌏', title: t('Globe Showing Asia-Australia') },
            { character: '🌐', title: t('Globe with Meridians') },
            { character: '🪨', title: t('Rock') },
            { character: '🌑', title: t('New Moon') },
            { character: '🌒', title: t('Waxing Crescent Moon') },
            { character: '🌔', title: t('Waxing Gibbous Moon') },
            { character: '🌕', title: t('Full Moon') },
            { character: '🌖', title: t('Waning Gibbous Moon') },
            { character: '🌗', title: t('Last Quarter Moon') },
            { character: '🌘', title: t('Waning Crescent Moon') },
            { character: '🌙', title: t('Crescent Moon') },
            { character: '🌚', title: t('New Moon Face') },
            { character: '🌛', title: t('First Quarter Moon Face') },
            { character: '🌜', title: t('Last Quarter Moon Face') },
            { character: '☀️', title: t('Sun') },
            { character: '🌝', title: t('Full Moon Face') },
            { character: '🌞', title: t('Sun with Face') },
            { character: '⭐', title: t('Star') },
            { character: '🌟', title: t('Glowing Star') },
            { character: '🌠', title: t('Shooting Star') },
            { character: '☁️', title: t('Cloud') },
            { character: '⛅', title: t('Sun Behind Cloud') },
            { character: '⛈️', title: t('Cloud with Lightning and Rain') },
            { character: '🌤️', title: t('Sun Behind Small Cloud') },
            { character: '🌥️', title: t('Sun Behind Large Cloud') },
            { character: '🌦️', title: t('Sun Behind Rain Cloud') },
            { character: '🌧️', title: t('Cloud with Rain') },
            { character: '🌨️', title: t('Cloud with Snow') },
            { character: '🌩️', title: t('Cloud with Lightning') },
            { character: '🌪️', title: t('Tornado') },
            { character: '🌫️', title: t('Fog') },
            { character: '🌬️', title: t('Wind Face') },
            { character: '🌈', title: t('Rainbow') },
            { character: '☂️', title: t('Umbrella') },
            { character: '☔', title: t('Umbrella with Rain Drops') },
            { character: '⚡', title: t('High Voltage') },
            { character: '❄️', title: t('Snowflake') },
            { character: '☃️', title: t('Snowman') },
            { character: '⛄', title: t('Snowman Without Snow') },
            { character: '☄️', title: t('Comet') },
            { character: '🔥', title: t('Fire') },
            { character: '💧', title: t('Droplet') },
            { character: '🌊', title: t('Water Wave') },
            { character: '🎄', title: t('Christmas Tree') },
            { character: '✨', title: t('Sparkles') },
            { character: '🎋', title: t('Tanabata Tree') },
            { character: '🎍', title: t('Pine Decoration') },
        ], { label: '🐹 ' + t('Nature') });
    }
}
